const HORIZONTAL_CELLS = 8;
const VERTICAL_CELLS = 6;
const CANVAS_WIDTH = window.innerWidth;
const CANVAS_HEIGHT = window.innerHeight;

const UNIT_LENGTH_X_AXIS = CANVAS_WIDTH / HORIZONTAL_CELLS;
const UNIT_LENGTH_Y_AXIS = CANVAS_HEIGHT / VERTICAL_CELLS;

KEY_CODE_W_KEY = 87;
KEY_CODE_Y_KEY = 89;
KEY_CODE_D_KEY = 68;
KEY_CODE_A_KEY = 65;
